# Generated by Django 4.1.7 on 2023-03-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="stdEmail",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="stdPhone",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
